format_version: 2
pipelines:
  gocd_test_demo:
    group: defaultGroup
    materials:
      backend:
        git: https://github.com/thompsm/gocd-test.git
        branch: master
    stages:
      - Demo_Stage_1:
          clean_workspace: true
          jobs:
            task1:
              tasks:
                - exec:
                    run_if: passed
                    command: ls 
                    arguments:
      - Demo_Stage_2:
          clean_workspace: true
          jobs:
            task2:
              tasks:
                - exec:
                    run_if: passed
                    command: pwd
